# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62c54e93888029c250ff6059de0fa787fa7089ef9c063aa0bc9ccb06f5f36a2b041c6924a74cbf00279c1364fc9759495d82ba8a8cb21325fbf86db0d46dff5e

test:
  secret_key_base: 7b01332581dcc5dd24560ad67ae2ef45145a34eb90c9cd456e31a8f3cf01dbfd144415fdf6357707c3033a787c38486c45c2b1fe6026e60b051b71551c41dd96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
